### ISSUE TITLE
Unable to reply

### ISSUE THREAD

**Issue by abrkn** [gabrielecirulli/hn-special#106]
### Steps to reproduce this issue
1. Go to the comments for post, such as https://news.ycombinator.com/item?id=12297530
2. Click "Reply" on a comment, such as https://news.ycombinator.com/reply?id=12297924&goto=item%3Fid%3D12297530%2312297924
### Expected result

Loaded page with comment box
### Actual result

Blank page

```
visual_theme.js:206 Uncaught TypeError: Cannot read property 'tagName' of undefined
(anonymous function) @ visual_theme.js:206
(anonymous function) @ visual_theme.js:161
Settings.runModule @ settings.js:86
(anonymous function) @ settings.js:63
(anonymous function) @ settings.js:62
```
### Notes and screenshots

![Fails to load](https://i.gyazo.com/36df60079c204ca3720fbdd090dbcf3f.png)

**Comment by PxlBuzzard** [comment]
The particular comment you linked to seems to be handled gracefully now (screenshot below). I can't replicate it elsewhere. My guess, based on your linked comment, is that Hacker News itself had a bug when replying to a comment marked as `[dupe]`.

![image](https://cloud.githubusercontent.com/assets/512416/22681648/32b66780-ecc3-11e6-801a-575a995df9ab.png)

**Comment by inverse** [comment]
Seeing this issue again

````
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getElementsByClassName')
    at Object.callback (visual_theme.js:88:39)
    at Settings.runModule (settings.js:72:46)
    at settings.js:49:14
    at Array.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (settings.js:48:24)
    at _.load (utility.js:16:16)
    at settings.js:45:7
    at utility.js:38:58
  ````
  
  Example: https://news.ycombinator.com/item?id=33150086 commenting on any of these.

**Comment by pratnala** [comment]
I am seeing the same issue as @inverse. Happens on every page and every comment. Replying is completely broken.

**Comment by inverse** [comment]
@pratnala PR'd a fix :crossed_fingers:

**Comment by inverse** [comment]
Is it published? I'm unable to find it in Chrome store
