### ISSUE TITLE
Feature:  Link within the comments open in new tab

### ISSUE THREAD

**Issue by FranciscoG** [gabrielecirulli/hn-special#107]
Every time I click on links within the comments of a post it opens the url within the same tab and when I go back I lose my place in the comments.   It would be great if hn-special could add target _blank to all links within comments.

![comments](http://i.imgur.com/vyNX5Ry.png)

**Comment by jiekeboy** [comment]
To learn how to read these recently

**Comment by PxlBuzzard** [comment]
Closing as a dupe of #21, which I see you also created some years ago :P We'll keep the discussion there.
