### ISSUE TITLE
Upvote/downvote arrows (all comment pages) are not lined up properly

### ISSUE THREAD

**Issue by dmix** [gabrielecirulli/hn-special#109]
See attached screenshot. Chaning the settings doesn't have an effect on this. Using the latest chrome-dev-unstable on ArchLinux:
![screenshot-window-16-10-13_3200_1800](https://cloud.githubusercontent.com/assets/12528/19357456/c841e868-913f-11e6-9642-766394ad27e6.png)

**Comment by PxlBuzzard** [comment]
I'm pretty sure I fixed this in `v1.4.8` that released yesterday, could you confirm or deny?
