### ISSUE TITLE
Release (signed) Mozilla extension

### ISSUE THREAD

**Issue by nfvs** [gabrielecirulli/hn-special#120]
The extension seems to build properly and can be used in Firefox without problems, but Mozilla requires extensions to be signed, otherwise there's no way to install them (the `xpinstall.signatures.required=false` override only works on the Developer edition).

Are there any plans to release it officially and sign it? I know there's an old .xpi in the releases, but lots of bugfixes have been submitted since.

The process seems relatively simple: https://developer.mozilla.org/en-US/Add-ons/Distribution

**Comment by aisk** [comment]
Just made a fork with just a few changes: https://github.com/aisk/hn-special/tree/fit-firefox
(Just changed the application id to avoid conflict, and flattened the zip file layout).

And released on FireFox addon store: https://addons.mozilla.org/zh-CN/firefox/addon/my-hn-special/ for people who want use it right now, and for a basic provement than hn-special can used under firefox now.

Feel free to contact me if hn-special's mantainer want to remove it on firefox store. @gabrielecirulli

**Comment by PxlBuzzard** [comment]
Thank you for making the changes @aisk. The problem you'll find if you try to move the extension from Experimental to Signed is that they have been blocking our release because of our usage of innerHTML, as documented in #88. However, I would be happy to accept your changes in a PR to this project.

**Comment by aisk** [comment]
@PxlBuzzard got it, thanks!

**Comment by PxlBuzzard** [comment]
I know this is old, but I wanted to update here and say that `v1.4.11` and the latest `v1.5.0` are officially signed and available under the [Releases tab](https://github.com/gabrielecirulli/hn-special/releases).
