### ISSUE TITLE
Infinite Scrolling does not display additional pages Mozilla

### ISSUE THREAD

**Issue by tjakab** [gabrielecirulli/hn-special#127]
As of about a week ago (around 26 September 2022), infinite scrolling does not display additional page content. Scrolling down will simply show "Page 2" with a line break, followed by "Page 3" and "Page 4" and so forth. It looks like something may have changed behind the scenes on the Hacker News site. 

Reproduced on Firefox 102.3.0 ESR on MacOS and Windows.

![Screen Shot 2022-10-02 at 9 47 37 AM](https://user-images.githubusercontent.com/11968199/193457423-c068af6c-ecef-482f-9268-72cdc5f2c0f4.png)

**Comment by darrenkopp** [comment]
same for chrome
