### ISSUE TITLE
Infinite scrolling is broken 

### ISSUE THREAD

**Issue by parin2092** [gabrielecirulli/hn-special#59]
now a days it shows only 
#### More
link 
![download](https://cloud.githubusercontent.com/assets/7147507/3745673/91804514-17b0-11e4-9bc4-5c21e64b020f.png)

Apparently , it is because HN changed the ULR structure to 
https://news.ycombinator.com/news?p=pageNo
previously it was different.

Please fix this LIFE sucks without it. :laughing:

**Comment by gabrielecirulli** [comment]
Should be fixed now. Thanks!

**Comment by gabrielecirulli** [comment]
(release coming in a few hours)
