### ISSUE TITLE
Infinite scroll doesnt work as it should

### ISSUE THREAD

**Issue by sjnonweb** [gabrielecirulli/hn-special#69]
Clicking "more" at the end of the page just opens up the next page in new tab or in the same tab in place of the current page. While i think it should open the next page in the same tab just below the current page, like continuous page.

Instead of having to click a link to get to the next set of posts, infinite scrolling should pull the next posts automatically into view when the reader approaches the bottom.

**Comment by gabrielecirulli** [comment]
Infinite scroll was broken, it should be restored in the next update! Thanks!
