### ISSUE TITLE
Uncaught TypeError in visual_theme.js line 200

### ISSUE THREAD

**Issue by alanc10n** [gabrielecirulli/hn-special#72]
An uncaught TypeError occurs on line 200 in visual_theme.js, resulting in missing up/down vote arrows (and possibly other issues with the page). The assignment of img on line 199 results in null, leading to the error on 200. Presumably the page source changed today, as this was working fine until some time today. 

This occurs in Chrome  41.0.2272.89 m on Windows 7 as well as 41.0.2272.118 on XUbuntu 14.04. 

Repro steps:

Load any HN item, e.g. https://news.ycombinator.com/item?id=9383905.
Open JS console and note this error, along with missing up/down arrows on all the comments.

**Comment by gabrielecirulli** [comment]
Thanks, I'll check it out. I also noticed that comments are rendering incorrectly, it might be related.

**Comment by pkrish** [comment]
+1
Cannot fold comments anymore.

**Comment by MrAlexWeber** [comment]
@pkrish, comment folding is noted in another issue and not directly related to this issue.

@gabrielecirulli this issue appears fixed by #75

**Comment by gabrielecirulli** [comment]
As mentioned in #75, this should be fixed by 2caab5f
