### ISSUE TITLE
Comment folding broken - "Hide Comments" links/button not showing up

### ISSUE THREAD

**Issue by boconnell** [gabrielecirulli/hn-special#73]
Just recently comment folding has broken for me, and the usual "Hide comments" (don't remember exact wording) are not showing up. I'm using Chrome Version 41.0.2272.118 (64-bit).

Screenshot: http://goo.gl/MecJb.

**Comment by dudevon** [comment]
Same here. Using Chrome on OSX `Version 41.0.2272.118 (64-bit)`

**Comment by dudevon** [comment]
It seems the issue is present with

```
// Skip this row if we're on a comment permalink page and it's the comment at the top
if (row.nextSibling && row.nextSibling.getElementsByClassName("yclinks").length) return;
```

`row.nextSibling` returns text element. This should be replaced by `row.nextElementSibling` which correctly returns the `<tr>` element

Example:
```
// Skip this row if we're on a comment permalink page and it's the comment at the top
if (row.nextElementSibling && row.nextElementSibling.getElementsByClassName("yclinks").length) return;
```

**Comment by unformatt** [comment]
Thanks for the fix. Unless I'm imagining how it used to work, folding would also fold up all the childred/reply comments. It's only folding the one comment after this fix.
