### ISSUE TITLE
Header looks broken

### ISSUE THREAD

**Issue by kwent** [gabrielecirulli/hn-special#86]
Since 2 or 3 days, header is broken ( See screenshot below )

<img width="1003" alt="screen shot 2016-01-26 at 10 26 14 am" src="https://cloud.githubusercontent.com/assets/879780/12590253/c80d5dec-c416-11e5-847f-7bd24013831e.png">

Thanks for you work !

Regards

**Comment by PxlBuzzard** [comment]
This is a duplicate of #81. However, last time the problem sorted itself out after a couple days and it was assumed it wouldn't come back.

**Comment by hugows** [comment]
I had the extension deactivated yesterday for this reason. :(

**Comment by PxlBuzzard** [comment]
This bug fixed itself for me a couple hours after I posted yesterday. Does anyone else still see the broken header?

**Comment by hugows** [comment]
It fixed itself because the black bar on HN was removed... but it will happen again when someone dies and Paul Graham puts a black bar for the day.

**Comment by kwent** [comment]
Oh make sense ! No we have an explanation !

**Comment by hugows** [comment]
Great! Thanks for the extension. I love some features but use the original visual theme!

**Comment by kwent** [comment]
Closing.
