### ISSUE TITLE
Convert to Web Extension

### ISSUE THREAD

**Issue by PxlBuzzard** [gabrielecirulli/hn-special#92]
[Firefox now accepts Web Extensions](https://blog.mozilla.org/addons/2016/07/14/webextensions-support-on-amo/).

**Comment by PxlBuzzard** [comment]
This work was completed in v1.4.6

**Comment by FichteFoll** [comment]
Where can I find this?

**Comment by FichteFoll** [comment]
Unfortunately, the .xpi on the releases page is unsigned and FF just redirects me [here](https://support.mozilla.org/t5/Problems-with-add-ons-plugins-or/Add-on-signing-in-Firefox/ta-p/30262) instead of installing it.

**Comment by PxlBuzzard** [comment]
I have a task to create an unofficial release of the Firefox addon that will be compatible with Firefox v48+. I would prefer to add it to Firefox Addons so we can more easily distribute updates going forward, but the Addon gatekeepers want a non-insignificant refactor before letting it onto the store (see #88).

**Comment by FichteFoll** [comment]
Thanks for the heads up. I was looking for a separate FireFox issue, but none of the open issues' titles hinted anything. I'll follow #88 for now.

(I also now remember that it was being mentioned in #33 as well.)
